services:
  landing:
    image: ghcr.io/fuggs-app/fuggs-landing:latest
    container_name: fuggs_landing
    restart: unless-stopped
    networks:
      - nginx-proxy-manager
networks:
  nginx-proxy-manager:
    external: true
